### ISSUE TITLE
Validate `dev.yml` Config

### ISSUE THREAD

**Issue by bosunski** [bosunski/dev#3]
```[tasklist]
### Tasks
- [ ] Use native types to represent some aspect of the config
- [ ] Create schema for `dev.yml`
- [ ] Validate parsed YAML based on schema
```
